 version: 2.1

 orbs:
  win: circleci/windows@3.0.0

 jobs:
   test:
     description: Run all tests
     executor:
      imagename: windows-server-2022-gui
      name: win/windows
      size: medium
      version: edge
     steps:
       - checkout
       - run: dotnet test -v n --results-directory:test_coverage --collect:"Code Coverage"
       - run: pwd
       - store_artifacts:
           path: C:\Users\circleci\project\test_coverage
  
   build:
     executor:
      imagename: windows-server-2022-gui
      name: win/windows
      size: medium
      version: edge
    
     steps:
       - checkout
       - run: dotnet build

 workflows:
   test_and_build:
     jobs:
       - test
       - build:
           requires:
             - test