 version: 2.1

 orbs:
  node: circleci/node@5.0.3

 jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          command: sudo apt update && sudo apt install -y dotnet6
          name: Install dotnet-skd-6.0
      - run:
          command: dotnet test -v n --results-directory:test_coverage --collect:"Code Coverage"
      - store_artifacts:
          path: ~/project/test_coverage
 workflows:
  test_my_app:
    jobs:
      - test