 version: 2.1

 orbs:
  debian: onehq/debian@1.0.0

 jobs:
   commands:
     install_common_tools:
       steps:
       - run:
           name: Install common tools
           command: |
             - sudo apt-get update && sudo apt-get install -y apt-transport-https && sudo apt-get update && sudo apt-get install -y dotnet-sdk-6.0
             - dotnet test -v n --results-directory:test_coverage --collect:"Code Coverage"
