 version: 2.1

 orbs:
  node: circleci/node@5.0.1

 jobs:
  test:
    executor:
      docker:
        - image: mcr.microsoft.com/dotnet/sdk
    steps:
      - checkout
      - run:
          command: dotnet test -v n --results-directory:test_coverage --collect:"Code Coverage"
      - run:
          command: pwd
      - store_artifacts:
          path: ~/project/test_coverage
 workflows:
  test_my_app:
    jobs:
      - test